Update docker-run

diff --git a/Unix/Scripts/custom/docker-run b/Unix/Scripts/custom/docker-run
--- a/Unix/Scripts/custom/docker-run
+++ b/Unix/Scripts/custom/docker-run
@@ -10,22 +10,99 @@
 #          "ls"
 #          "./build"
 #        ```
-#  - A `docker-compose.yml` has to be located in the `$GIT_ROOT` or inside `$GIT_ROOT/local` and
-#    has to configure three services, each one using an image with one of the following prefixes:
-#      * `native/`
-#      * `armv7/`
-#      * `arm64v8/`
+# - A `docker-compose.yml` has to be located in the `$GIT_ROOT` or inside `$GIT_ROOT/local` and
+#   has to configure three services for full support, each one specifying a different platform:
+#     * `linux/amd64`
+#     * `linux/arm/v7`
+#     * `linux/arm64/v8`
+# 
+# Afterwards, simply create two symbolic links `arm-run` and `arm8-run` or simply use 
+# `docker-run install-links` and be ready to run any command in an armv7, armv8 or amd64
+# docker environment, using e.g. `docker-run ls`
 #
-# Setup:
-#  - Place the script in any directory specified in the path
-#  - Create symbolic links to the script, naming the links `arm-run` and `arm8-run`
-#
+# At runtime the information about running docker containers managed by the script is located
+# at /tmp/docker-run
 
 RED="\e[31m"
 GREEN="\e[32m"
 YELLOW="\e[33m"
 BLUE="\e[34m"
 RESET="\e[0m"
+
+# Install symbolic links
+if [ "$1" == "install-links" ]; then
+    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
+    if [ ! -f "$SCRIPT_DIR/arm-run" ]; then
+        echo -e "$YELLOW[!]$RESET Install symbolic link '$BLUE$SCRIPT_DIR/arm-run$RESET'"
+        ln -sf "$SCRIPT_DIR/docker-run" "$SCRIPT_DIR/arm-run"
+        chmod +x "$SCRIPT_DIR/arm-run"
+    elif [ ! -f "$SCRIPT_DIR/arm8-run" ]; then
+        echo -e "$YELLOW[!]$RESET Install symbolic link '$BLUE$SCRIPT_DIR/arm8-run$RESET'"
+        ln -sf "$SCRIPT_DIR/docker-run" "$SCRIPT_DIR/arm8-run"
+        chmod +x "$SCRIPT_DIR/arm8-run"
+    else
+        echo -e "$YELLOW[$GREEN!$YELLOW]$RESET Symbolic links '$BLUE$SCRIPT_DIR/arm-run$RESET' and '$BLUE$SCRIPT_DIR/arm8-run$RESET' already present."
+    fi
+    exit 0
+fi
+
+# Remove quotes
+unquote() {
+    VALUE="$@"
+    if [ -z "$(echo $VALUE | cut -f1 -d"'")" ]; then
+        echo $(echo $VALUE | cut -f2- -d"'" | rev | cut -f2- -d"'" | rev)
+    elif [ -z "$(echo $VALUE | cut -f1 -d'"')" ]; then
+        echo $(echo $VALUE | cut -f2- -d'"' | rev | cut -f2- -d'"' | rev)
+    else
+        echo $@
+    fi
+}
+
+# Yaml parser to XPath
+parse_yaml() {
+    FILENAME=$1
+
+    if [ -z "$FILENAME" ]; then
+        echo -e "${RED}Abort:$RESET No file specified"
+        exit 1
+    fi
+
+    PREV_INDENT=0
+    XPATH=""
+    LAST_XPATH=""
+
+    while IFS= read -r line; do
+        INDENT=0
+
+        STRIPPED="$(echo $line)"
+        if [[ "$STRIPPED" =~ ^-.* ]]; then
+            ITEM="$(echo $(echo $STRIPPED | cut -f2- -d'-'))"
+            echo "$LAST_XPATH=$(unquote $ITEM)"
+        else
+            # Get indentation level
+            while [ -z "$(echo "$line" | cut -f$((INDENT + 1)) -d' ')" ]; do
+                INDENT=$(($INDENT + 1))
+            done
+
+            if [ $INDENT -ne $PREV_INDENT ]; then
+                # Remove last part
+                if [ $INDENT -lt $PREV_INDENT ]; then
+                    XPATH=$(echo $XPATH | rev | cut -f2- -d'.' | rev)
+                elif [ $INDENT -gt $PREV_INDENT ]; then
+                    XPATH=$LAST_XPATH
+                fi
+                PREV_INDENT=$INDENT
+            fi
+
+            LABEL="$(echo $line | cut -f1 -d':')"
+            VALUE="$(echo $(echo $line | cut -f2- -d':'))"
+            if [ ! -z "$VALUE" ]; then
+                echo "${XPATH}.${LABEL}=$(unquote $VALUE)"
+            fi
+            LAST_XPATH="${XPATH}.${LABEL}"
+        fi
+    done < <(cat $FILENAME)
+}
 
 # Since we utilize the symlink arm-run to execute commands in an armv7
 # environment, we check for the executable name to determine the container
@@ -44,39 +121,44 @@ while [ ! -z "${CUR_DIR}" ] && [ ! -d "${CUR_DIR}/.git" ]; do
     CUR_DIR=$(dirname ${CUR_DIR})
 done
 
-DOCKER_COMPOSE_DIR=""
-if [ -f "$CUR_DIR/docker-compose.yml" ]; then
-    DOCKER_COMPOSE_DIR="$CUR_DIR"
-elif [ -f "$CUR_DIR/local/docker-compose.yml" ]; then
-    DOCKER_COMPOSE_DIR="$CUR_DIR/local"
-elif [ -f "$WORKDIR/docker-compose.yml" ]; then
-    DOCKER_COMPOSE_DIR="$WORKDIR"
+# Get directory containing given file
+locate_file() {
+    if [ -f "$CUR_DIR/$1" ]; then
+        echo "$CUR_DIR"
+    elif [ -f "$CUR_DIR/local/$1" ]; then
+        echo "$CUR_DIR/local"
+    elif [ -f "$WORKDIR/$1" ]; then
+        echo "$WORKDIR"
+    else
+        echo -e "$RED[E]$RESET Unable to locate '${BLUE}$1$RESET'"
+        exit 1
+    fi
+}
+
+DOCKER_COMPOSE_DIR="$(locate_file docker-compose.yml)"
+CONTAINER_NAME="$(basename $WORKDIR)"
+
+# Specify compose target platform
+if [ "$NAME" == "arm-run" ]; then
+    DOCKER_COMPOSE_PLATFORM="linux/arm/v7"
+elif [ "$NAME" == "arm8-run" ]; then
+    DOCKER_COMPOSE_PLATFORM="linux/arm64/v8"
 else
-    echo -e "$RED[E]$RESET Unable to locate '${BLUE}docker-compose.yml$RESET'"
+    DOCKER_COMPOSE_PLATFORM="linux/amd64"
 fi
 
-if [ "$NAME" == "arm-run" ]; then
-    CONTAINER_NAME="armv7/$(cat $DOCKER_COMPOSE_DIR/docker-compose.yml | grep 'image: armv7/' | cut -f2 -d'/' | cut -f1 -d':')"
-    DOCKER_COMPOSE_TARGET="armv7"
-elif [ "$NAME" == "arm8-run" ]; then
-    CONTAINER_NAME="arm64v8/$(cat $DOCKER_COMPOSE_DIR/docker-compose.yml | grep 'image: arm64v8/' | cut -f2 -d'/' | cut -f1 -d':')"
-    DOCKER_COMPOSE_TARGET="armv8"
-else
-    CONTAINER_NAME="native/$(cat $DOCKER_COMPOSE_DIR/docker-compose.yml | grep 'image: native/' | cut -f2 -d'/' | cut -f1 -d':')"
-    DOCKER_COMPOSE_TARGET="native"
-fi
+DOCKER_COMPOSE_TARGET=$(parse_yaml "$DOCKER_COMPOSE_DIR/docker-compose.yml" | grep platform | grep $DOCKER_COMPOSE_PLATFORM | cut -f3 -d'.')
 
 GIT_DIR=$CUR_DIR
+GIT_BASENAME=$(echo "P$GIT_DIR" | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]')
 
-GIT_BASENAME=$(basename "$GIT_DIR")
-
-CONTAINER_ID=$(docker container ls | grep "$CONTAINER_NAME" | cut -f1 -d' ')
+CONTAINER_ID=$(docker container ls | grep "$GIT_BASENAME-$DOCKER_COMPOSE_TARGET" | cut -f1 -d' ')
 if [ ! -z "$CONTAINER_ID" ]; then
     if [ ! -f "/tmp/docker-run" ]; then
         echo -e "$YELLOW[!]$RESET Stop running container $BLUE$CONTAINER_ID$RESET"
         docker stop $CONTAINER_ID &>/dev/null
     else
-        DIR="$(cat /tmp/docker-run | grep "$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=" | cut -f2- -d'=')"
+        DIR="$(parse_yaml /tmp/docker-run | grep "$DOCKER_COMPOSE_PLATFORM-$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=" | cut -f2- -d'=')"
         if [ -z "$DIR" ] || [ "$DIR" != "$GIT_DIR" ]; then
             echo -e "$YELLOW[!]$RESET Stop running container $BLUE$CONTAINER_ID$RESET"
             docker stop $CONTAINER_ID &>/dev/null
@@ -100,17 +182,15 @@ else
 fi
 
 if [ ! -f "/tmp/docker-run" ]; then
-    echo "$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=$GIT_DIR" >> /tmp/docker-run
+    echo "$DOCKER_COMPOSE_PLATFORM-$DOCKER_COMPOSE_TARGET-$GIT_BASENAME: $GIT_DIR" >> /tmp/docker-run
 else
-    if [ -z "$(cat /tmp/docker-run | grep "$DOCKER_COMPOSE_TARGET-$GIT_BASENAME")" ]; then
-        echo "$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=$GIT_DIR" >> /tmp/docker-run
-    else
-        sed -i "s,$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=.*,$DOCKER_COMPOSE_TARGET-$GIT_BASENAME=$GIT_DIR,g" /tmp/docker-run
-    fi
+    cat /tmp/docker-run | grep -v "$DOCKER_COMPOSE_PLATFORM-$DOCKER_COMPOSE_TARGET-$GIT_BASENAME:" > /tmp/docker-run-tmp
+    mv /tmp/docker-run-tmp /tmp/docker-run
+    echo "$DOCKER_COMPOSE_PLATFORM-$DOCKER_COMPOSE_TARGET-$GIT_BASENAME: $GIT_DIR" >> /tmp/docker-run
 fi
 
 # Get container id
-CONTAINER_ID=$(docker container ls | grep "$CONTAINER_NAME" | cut -f1 -d' ')
+CONTAINER_ID=$(docker container ls | grep "$GIT_BASENAME-$DOCKER_COMPOSE_TARGET" | cut -f1 -d' ')
 
 # Abort if container isn't running
 if [ -z "$CONTAINER_ID" ]; then
@@ -133,7 +213,8 @@ if [ -z "$CONTAINER_ID" ]; then
     fi
 fi
 
-CONTAINER_ID=$(docker container ls | grep "$CONTAINER_NAME" | cut -f1 -d' ')
+CONTAINER_ID=$(docker container ls | grep "$GIT_BASENAME-$DOCKER_COMPOSE_TARGET" | cut -f1 -d' ')
+echo -e "$YELLOW[!]$RESET Use container: '$BLUE$CONTAINER_ID$RESET'"
 
 # Detect relative path from repository root
 if [ ! -z ${CUR_DIR} ]; then
