Update git-hooks

diff --git a/Unix/Scripts/git-cmd/git-hooks b/Unix/Scripts/git-cmd/git-hooks
--- a/Unix/Scripts/git-cmd/git-hooks
+++ b/Unix/Scripts/git-cmd/git-hooks
@@ -1,105 +1,105 @@
 #!/bin/env bash
 
-COMMIT_MSG_HOOK_CHECK_TAG='#!/usr/bin/env bash
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+COMMIT_MSG_HOOK_CHECK_TAG=$(echo '#!/usr/bin/env bash\n' \
+'SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )\n' \
+'\n' \
+'OUTPUT_FILE="$1"\n' \
+'\n' \
+'if [ -z "$OUTPUT_FILE" ]; then\n' \
+'    echo -e "\e[31mERROR: Missing output file.\e[0m"\n' \
+'    exit 1\n' \
+'else\n' \
+'    REGEX="([A-Z]+-[0-9]+)"\n' \
+'    BRANCH="$(git branch --show-current)"\n' \
+'\n' \
+'    if [[ $BRANCH =~ $REGEX ]]; then\n' \
+'        HEAD="$(head -1 $OUTPUT_FILE)"\n' \
+'        echo "$HEAD" | grep -q "\[${BASH_REMATCH[1]}\]"\n' \
+'        if [ $? -ne 0 ]; then\n' \
+'            echo -e "\e[31mERROR: Commit aborted. Tag is missing in commit msg.\e[0m"\n' \
+'            exit 1\n' \
+'        fi\n' \
+'\n' \
+'        REGEX="^[[:space:]]*\[${BASH_REMATCH[1]}\][[:space:]]*$"\n' \
+'        if [[ $HEAD =~ $REGEX ]]; then\n' \
+'            echo -e "\e[31mERROR: Commit aborted. No commit message provided.\e[0m"\n' \
+'            exit 1\n' \
+'        fi\n' \
+'    fi\n' \
+'fi')
 
-OUTPUT_FILE="$1"
+PRE_COMMIT_HOOK_FOR_CLANG_FORMAT=$(echo '#!/usr/bin/env bash\n' \
+'\n' \
+'script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )\n' \
+'\n' \
+'cd "$script_dir/../"\n' \
+'\n' \
+'if [ -z "$(which clang-format)" ]; then\n' \
+'    echo -e "\\n\e[31m  ERROR: Commit aborted. Formatter clang-format is missing. Please install clang-format for style check.\e[0m\\n"\n' \
+'    exit 1\n' \
+'fi\n' \
+'\n' \
+'version=$(clang-format --version | cut -f4 -d'' '' | cut -f1 -d''.'')\n' \
+'if [ $version -lt 18 ]; then\n' \
+'    echo -e "\\n\e[31m  ERROR: Commit aborted. Only clang-format v18+ is supported. Please update clang-format.\e[0m\\n"\n' \
+'    exit 1\n' \
+'fi\n' \
+'\n' \
+'files=()\n' \
+'for file in `git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(c|cpp|cxx|cc|h|hpp|hxx)$"`; do\n' \
+'    output="$(cmp -b <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))"\n' \
+'    if [ $? -ne 0 ]; then\n' \
+'        files+=("${file}")\n' \
+'    fi\n' \
+'done\n' \
+'\n' \
+'if [ -n "${files}" ]; then\n' \
+'    echo -e "\n  \e[33mAffected files:\e[0m\n"\n' \
+'    for file in ${files[@]}; do\n' \
+'        printf "    - %s\n\n" "${files[@]}"\n' \
+'\n' \
+'        lnum=1\n' \
+'        while IFS= read -r line; do\n' \
+'            if [ $lnum -lt 3 ]; then\n' \
+'                echo -e "          | \e[01;97m$line\e[0m"\n' \
+'            elif [ $lnum -eq 3 ]; then\n' \
+'                echo -e "          | \e[36m$line\e[0m"\n' \
+'            elif [[ $line == +* ]]; then\n' \
+'                echo -e "          | \e[32m$line\e[0m"\n' \
+'            elif [[ $line == -* ]]; then\n' \
+'                echo -e "          | \e[31m$line\e[0m"\n' \
+'            else\n' \
+'                echo -e "          | $line"\n' \
+'            fi\n' \
+'            lnum=$((lnum+1))\n' \
+'        done < <(diff --color -u <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))\n' \
+'        echo\n' \
+'    done\n' \
+'    echo -e "\e[31m  ERROR: Commit aborted. Changes do not match with code style. Run clang-format first.\e[0m\\n"\n' \
+'    exit 1\n' \
+'fi')
 
-if [ -z "$OUTPUT_FILE" ]; then
-    echo -e "\e[31mERROR: Missing output file.\e[0m"
-    exit 1
-else
-    REGEX="([A-Z]+-[0-9]+)"
-    BRANCH="$(git branch --show-current)"
-
-    if [[ $BRANCH =~ $REGEX ]]; then
-        HEAD="$(head -1 $OUTPUT_FILE)"
-        echo "$HEAD" | grep -q "\[${BASH_REMATCH[1]}\]"
-        if [ $? -ne 0 ]; then
-            echo -e "\e[31mERROR: Commit aborted. Tag is missing in commit msg.\e[0m"
-            exit 1
-        fi
-
-        REGEX="^[[:space:]]*\[${BASH_REMATCH[1]}\][[:space:]]*$"
-        if [[ $HEAD =~ $REGEX ]]; then
-            echo -e "\e[31mERROR: Commit aborted. No commit message provided.\e[0m"
-            exit 1
-        fi
-    fi
-fi'
-
-PRE_COMMIT_HOOK_FOR_CLANG_FORMAT='#!/usr/bin/env bash
-
-script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-
-cd "$script_dir/../"
-
-if [ -z "$(which clang-format)" ]; then
-    echo -e "\n\e[31m  ERROR: Commit aborted. Formatter clang-format is missing. Please install clang-format for style check.\e[0m\n"
-    exit 1
-fi
-
-version=$(clang-format --version | cut -f4 -d' ' | cut -f1 -d'.')
-if [ $version -lt 18 ]; then
-    echo -e "\n\e[31m  ERROR: Commit aborted. Only clang-format v18+ is supported. Please update clang-format.\e[0m\n"
-    exit 1
-fi
-
-files=()
-for file in `git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(c|cpp|cxx|cc|h|hpp|hxx)$"`; do
-    output="$(cmp -b <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))"
-    if [ $? -ne 0 ]; then
-        files+=("${file}")
-    fi
-done
-
-if [ -n "${files}" ]; then
-    echo -e "\n  \e[33mAffected files:\e[0m\n"
-    for file in ${files[@]}; do
-        printf "    - %s\n\n" "${files[@]}"
-
-        lnum=1
-        while IFS= read -r line; do
-            if [ $lnum -lt 3 ]; then
-                echo -e "          | \e[01;97m$line\e[0m"
-            elif [ $lnum -eq 3 ]; then
-                echo -e "          | \e[36m$line\e[0m"
-            elif [[ $line == +* ]]; then
-                echo -e "          | \e[32m$line\e[0m"
-            elif [[ $line == -* ]]; then
-                echo -e "          | \e[31m$line\e[0m"
-            else
-                echo -e "          | $line"
-            fi
-            lnum=$((lnum+1))
-        done < <(diff --color -u <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))
-        echo
-    done
-    echo -e "\e[31m  ERROR: Commit aborted. Changes do not match with code style. Run clang-format first.\e[0m\n"
-    exit 1
-fi'
-
-PREPARE_COMMIT_MSG_JIRA_TAG='#!/bin/env bash
-
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-
-COMMIT_MSG="$1"
-
-if [ -z "$COMMIT_MSG" ]; then
-    echo -e "\e[31mERROR: Commit aborted. Missing argument in prepare-commit-msg.\e[0m"
-    exit 1
-else
-    if [ ! -z "$(cat $COMMIT_MSG)" ]; then
-        exit 0
-    fi
-
-    REGEX="([A-Z]+-[0-9]+)"
-    BRANCH="$(/usr/bin/git branch --show-current)"
-
-    if [[ $BRANCH =~ $REGEX ]]; then
-        echo "[${BASH_REMATCH[1]}] " > "$COMMIT_MSG"
-    fi
-fi'
+PREPARE_COMMIT_MSG_JIRA_TAG=$(echo '#!/bin/env bash\n' \
+'\n' \
+'SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )\n' \
+'\n' \
+'COMMIT_MSG="$1"\n' \
+'\n' \
+'if [ -z "$COMMIT_MSG" ]; then\n' \
+'    echo -e "\e[31mERROR: Commit aborted. Missing argument in prepare-commit-msg.\e[0m"\n' \
+'    exit 1\n' \
+'else\n' \
+'    if [ ! -z "$(cat $COMMIT_MSG)" ]; then\n' \
+'        exit 0\n' \
+'    fi\n' \
+'\n' \
+'    REGEX="([A-Z]+-[0-9]+)"\n' \
+'    BRANCH="$(/usr/bin/git branch --show-current)"\n' \
+'\n' \
+'    if [[ $BRANCH =~ $REGEX ]]; then\n' \
+'        echo "[${BASH_REMATCH[1]}] " > "$COMMIT_MSG"\n' \
+'    fi\n' \
+'fi')
 
 root_dir() {
     ROOT_DIR="$(pwd)"
@@ -150,14 +150,14 @@ cd "${ROOT_DIR}"
 
 echo ""
 if [ -z "$1" ] || [ "$1" == "install" ]; then
-    echo -e "  \e[33mInstall git hooks\e[0m\n"
+    echo -e "  \e[34mInstall git hooks\e[0m\n"
 
     echo '#!/bin/env bash
 
     if [ -x $0.local ]; then
         $0.local "$@" || exit $?
     fi
-    
+
     HOOK="$(dirname $0)/../../.git-hooks/$(basename $0)"
     if [ -x "$HOOK" ]; then
         $HOOK "$@" || exit $?
@@ -166,27 +166,32 @@ if [ -z "$1" ] || [ "$1" == "install" ]; then
     for f in ${GIT_HOOK_DIR}/*; do
         chmod +x $f
     done' > "${GIT_HOOK_DIR}/hooks-wrapper"
-    
+
     chmod +x "${GIT_HOOK_DIR}/hooks-wrapper"
 
-    echo -ne "  [\e[33m?\e[0m] Install PREPARE_COMMIT hook for Jira tags? [Y/n] " 1>&2
-    read value
-    if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then        
-        (echo "$PREPARE_COMMIT_MSG_JIRA_TAG" > "${GIT_HOOK_DIR}/prepare-commit-msg" && chmod +x "${GIT_HOOK_DIR}/prepare-commit-msg" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
-    fi
-
-    echo -ne "  [\e[33m?\e[0m] Install PRE_COMMIT hook for clang-format? [Y/n] " 1>&2
+    echo -ne "  \e[34m    Install PREPARE_COMMIT hook for Jira tags? [Y/n] \e[0m" 1>&2
     read value
     if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then
-        (echo "$PRE_COMMIT_HOOK_FOR_CLANG_FORMAT" > "${GIT_HOOK_DIR}/pre-commit" && chmod +x "${GIT_HOOK_DIR}/pre-commit" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
+        echo -n "          Install hook ... "
+        (echo -e "$PREPARE_COMMIT_MSG_JIRA_TAG" > "${GIT_HOOK_DIR}/prepare-commit-msg" && chmod +x "${GIT_HOOK_DIR}/prepare-commit-msg" && echo -e "\e[32minstalled\e[0m")  || echo -e "\e[31mfailed\e[0m"
     fi
+    echo ""
 
-    echo -ne "  [\e[33m?\e[0m] Install COMMIT_MSG hook for Jira tag check? [Y/n] " 1>&2
+    echo -ne "  \e[34m    Install PRE_COMMIT hook for clang-format? [Y/n] \e[0m" 1>&2
     read value
     if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then
-        echo -n "    commit-msg ... "
-        (echo "$COMMIT_MSG_HOOK_CHECK_TAG" > "${GIT_HOOK_DIR}/commit-msg" && chmod +x "${GIT_HOOK_DIR}/commit-msg" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
+        echo -n "          Install hook ... "
+        (echo -e "$PRE_COMMIT_HOOK_FOR_CLANG_FORMAT" > "${GIT_HOOK_DIR}/pre-commit" && chmod +x "${GIT_HOOK_DIR}/pre-commit" && echo -e "\e[32minstalled\e[0m")  || echo -e "\e[31mfailed\e[0m"
     fi
+    echo ""
+
+    echo -ne "  \e[34m    Install COMMIT_MSG hook for Jira tag check? [Y/n] \e[0m" 1>&2
+    read value
+    if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then
+        echo -n "          Install hook ... "
+        (echo -e "$COMMIT_MSG_HOOK_CHECK_TAG" > "${GIT_HOOK_DIR}/commit-msg" && chmod +x "${GIT_HOOK_DIR}/commit-msg" && echo -e "\e[32minstalled\e[0m")  || echo -e "\e[31mfailed\e[0m"
+    fi
+    echo ""
 
     HOOK_DIR="${GIT_DIR}/hooks"
     cd "${HOOK_DIR}"
